version: '3.7'

services:
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    container_name: opensearch
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - DISABLE_INSTALL_DEMO_CONFIG=true # Desactiva seguridad demo si quieres configurar la tuya
      - DISABLE_SECURITY_PLUGIN=true      # El truco para desarrollo sin contraseñas ni HTTPS
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    ports:
      - 9200:9200
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.12.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_PLUGIN=true
    depends_on:
      - opensearch
    networks:
      - opensearch-net

volumes:
  opensearch_data:
    driver: local

networks:
  opensearch-net:
    driver: bridge